### PR TITLE
Compile against upstream librespot.

### LINKED ISSUE #669: librespot error: Unable to load encrypted file: ChannelError
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

I've newly installed raspotify, first time I've tried it (apologies in advance if I've messed up). I've checked all packages are up to date. Able to connect but, so far, unable to play any tracks. The Spotify app it skips a number of tracks and then drops the connection. Raspotify crashes.

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
seb@woody2:~ $ sudo systemctl status raspotify
○ raspotify.service - Raspotify (Spotify Connect Client)
     Loaded: loaded (/lib/systemd/system/raspotify.service; enabled; preset: enabled)
     Active: inactive (dead) since Tue 2024-09-03 11:15:42 BST; 10s ago
   Duration: 20min 18.446s
       Docs: https://github.com/dtcooper/raspotify
             https://github.com/librespot-org/librespot
             https://github.com/dtcooper/raspotify/wiki
             https://github.com/librespot-org/librespot/wiki/Options
    Process: 2057 ExecStart=/usr/bin/librespot (code=exited, status=1/FAILURE)
   Main PID: 2057 (code=exited, status=1/FAILURE)
        CPU: 886ms

Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyI>
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyI>
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_playback::player] Player::pause called from invalid state
Sep 03 11:15:42 woody2 systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 11:15:42 woody2 systemd[1]: raspotify.service: Failed with result 'exit-code'.
Sep 03 11:15:42 woody2 systemd[1]: raspotify.service: Triggering OnFailure= dependencies.

seb@woody2:~ $ sudo cat /etc/raspotify/crash_report
-- System Info --

Linux woody2 6.6.31+rpt-rpi-v7 #1 SMP Raspbian 1:6.6.31-1+rpt1 (2024-05-29) armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

-- Logs --

Sep 03 11:15:20 woody2 librespot[2057]: [2024-09-03T10:15:20Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:20 woody2 librespot[2057]: [2024-09-03T10:15:20Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:20 woody2 librespot[2057]: [2024-09-03T10:15:20Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 126806494954782361247359943464033853241, audio_type: Track }>: ()
Sep 03 11:15:21 woody2 librespot[2057]: [2024-09-03T10:15:21Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:21 woody2 librespot[2057]: [2024-09-03T10:15:21Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:21 woody2 librespot[2057]: [2024-09-03T10:15:21Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:21 woody2 librespot[2057]: [2024-09-03T10:15:21Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:21 woody2 librespot[2057]: [2024-09-03T10:15:21Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 320158299921808252690735751775098227393, audio_type: Track }>: ()
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 52621951561035753325778871631505391361, audio_type: Track }>: ()
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 126232793412268778699170059956979978348, audio_type: Track }>: ()
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:22 woody2 librespot[2057]: [2024-09-03T10:15:22Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 38462256543178713776523463958669243869, audio_type: Track }>: ()
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 294226554747449571944054822840118140828, audio_type: Track }>: ()
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 238650096479037371193508542714067408625, audio_type: Track }>: ()
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:23 woody2 librespot[2057]: [2024-09-03T10:15:23Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 290275184107914125879401380138287603312, audio_type: Track }>: ()
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 76231440952378343749429875858611029964, audio_type: Track }>: ()
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 162565175161683117874000095560583879629, audio_type: Track }>: ()
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 174677382660820724948302506964788073399, audio_type: Track }>: ()
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:24 woody2 librespot[2057]: [2024-09-03T10:15:24Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 334084673601181082788724283531108341013, audio_type: Track }>: ()
Sep 03 11:15:25 woody2 librespot[2057]: [2024-09-03T10:15:25Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:25 woody2 librespot[2057]: [2024-09-03T10:15:25Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:25 woody2 librespot[2057]: [2024-09-03T10:15:25Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 63955398560496241187807381585403052673, audio_type: Track }>: ()
Sep 03 11:15:25 woody2 librespot[2057]: [2024-09-03T10:15:25Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:25 woody2 librespot[2057]: [2024-09-03T10:15:25Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:25 woody2 librespot[2057]: [2024-09-03T10:15:25Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 237387852502678357132700074303167398284, audio_type: Track }>: ()
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 167904913271618366697744884595623010836, audio_type: Track }>: ()
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 91932003364606595579902896507233787496, audio_type: Track }>: ()
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 257775688650951142620540649080049521563, audio_type: Track }>: ()
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:26 woody2 librespot[2057]: [2024-09-03T10:15:26Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 238650096479037371193508542714067408625, audio_type: Track }>: ()
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 74745788335471553945327228076819511332, audio_type: Track }>: ()
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 87480308384661780904389899737106314882, audio_type: Track }>: ()
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 185443135188129991553604145626869012521, audio_type: Track }>: ()
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 1070466098558975767873163126502995758, audio_type: Track }>: ()
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:27 woody2 librespot[2057]: [2024-09-03T10:15:27Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 177130946809687736906416366157010731137, audio_type: Track }>: ()
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 38462256543178713776523463958669243869, audio_type: Track }>: ()
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 98038554834506001040200258282265599888, audio_type: Track }>: ()
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:28 woody2 librespot[2057]: [2024-09-03T10:15:28Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 251725838406764927002748285611301917475, audio_type: Track }>: ()
Sep 03 11:15:29 woody2 librespot[2057]: [2024-09-03T10:15:29Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:29 woody2 librespot[2057]: [2024-09-03T10:15:29Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:29 woody2 librespot[2057]: [2024-09-03T10:15:29Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 130765248527077979583505292425743218220, audio_type: Track }>: ()
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 192296242641145414903328848787383356072, audio_type: Track }>: ()
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 92537201111000702701931466352706050388, audio_type: Track }>: ()
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:30 woody2 librespot[2057]: [2024-09-03T10:15:30Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 334084673601181082788724283531108341013, audio_type: Track }>: ()
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 187248081370458789403947603811886294405, audio_type: Track }>: ()
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 177345914530032593031944422978124850104, audio_type: Track }>: ()
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 155687839428143680945309904370511205900, audio_type: Track }>: ()
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:31 woody2 librespot[2057]: [2024-09-03T10:15:31Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 71887251042537302813054194956969778286, audio_type: Track }>: ()
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 161725278881200019753034066875414562701, audio_type: Track }>: ()
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 52621951561035753325778871631505391361, audio_type: Track }>: ()
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:32 woody2 librespot[2057]: [2024-09-03T10:15:32Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 146889970772958698268820676605105552564, audio_type: Track }>: ()
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 270313825394035309909089438574764647650, audio_type: Track }>: ()
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 301575444881287594631368691252306422112, audio_type: Track }>: ()
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 225023191424127838807942939887532127825, audio_type: Track }>: ()
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:33 woody2 librespot[2057]: [2024-09-03T10:15:33Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 74119274716365450089928730495976128438, audio_type: Track }>: ()
Sep 03 11:15:34 woody2 librespot[2057]: [2024-09-03T10:15:34Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:34 woody2 librespot[2057]: [2024-09-03T10:15:34Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:34 woody2 librespot[2057]: [2024-09-03T10:15:34Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 224044008265187341691576296599589364422, audio_type: Track }>: ()
Sep 03 11:15:34 woody2 librespot[2057]: [2024-09-03T10:15:34Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:34 woody2 librespot[2057]: [2024-09-03T10:15:34Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:34 woody2 librespot[2057]: [2024-09-03T10:15:34Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 165031183745367397803559027319143945171, audio_type: Track }>: ()
Sep 03 11:15:35 woody2 librespot[2057]: [2024-09-03T10:15:35Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:35 woody2 librespot[2057]: [2024-09-03T10:15:35Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:35 woody2 librespot[2057]: [2024-09-03T10:15:35Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 190039128357124004785304595946050551554, audio_type: Track }>: ()
Sep 03 11:15:36 woody2 librespot[2057]: [2024-09-03T10:15:36Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:36 woody2 librespot[2057]: [2024-09-03T10:15:36Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:36 woody2 librespot[2057]: [2024-09-03T10:15:36Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 171789151617016032879725344619141912960, audio_type: Track }>: ()
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 217132563484251462607426520503440229246, audio_type: Track }>: ()
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 256613941167788935553955746274420849751, audio_type: Track }>: ()
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:37 woody2 librespot[2057]: [2024-09-03T10:15:37Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 294226554747449571944054822840118140828, audio_type: Track }>: ()
Sep 03 11:15:38 woody2 librespot[2057]: [2024-09-03T10:15:38Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:38 woody2 librespot[2057]: [2024-09-03T10:15:38Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:38 woody2 librespot[2057]: [2024-09-03T10:15:38Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 86624718332552533022607502088552396427, audio_type: Track }>: ()
Sep 03 11:15:38 woody2 librespot[2057]: [2024-09-03T10:15:38Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:38 woody2 librespot[2057]: [2024-09-03T10:15:38Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:38 woody2 librespot[2057]: [2024-09-03T10:15:38Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 100169465575007697204039211471001724000, audio_type: Track }>: ()
Sep 03 11:15:39 woody2 librespot[2057]: [2024-09-03T10:15:39Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:39 woody2 librespot[2057]: [2024-09-03T10:15:39Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:39 woody2 librespot[2057]: [2024-09-03T10:15:39Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 3984120001878050883103028583011869328, audio_type: Track }>: ()
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 95293188025346898249021954054211711569, audio_type: Track }>: ()
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 335092724815006547868597750200623844407, audio_type: Track }>: ()
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 290275184107914125879401380138287603312, audio_type: Track }>: ()
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:40 woody2 librespot[2057]: [2024-09-03T10:15:40Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 45076626636866408682939568510910396277, audio_type: Track }>: ()
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 274844126256630504698732599479696179881, audio_type: Track }>: ()
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 92998624915036665191064150904319423699, audio_type: Track }>: ()
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:41 woody2 librespot[2057]: [2024-09-03T10:15:41Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 193904654964920356766379881822163502708, audio_type: Track }>: ()
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 91190659776345566378754501615850850513, audio_type: Track }>: ()
Sep 03 11:15:42 woody2 librespot[2057]: [2024-09-03T10:15:42Z ERROR librespot_playback::player] Player::pause called from invalid state
Sep 03 11:15:42 woody2 systemd[1]: raspotify.service: Main process exited, code=exited, status=1/FAILURE
Sep 03 11:15:42 woody2 systemd[1]: raspotify.service: Failed with result 'exit-code'.
Sep 03 11:15:42 woody2 systemd[1]: raspotify.service: Triggering OnFailure= dependencies.

-- Config --

LIBRESPOT_QUIET=
LIBRESPOT_AUTOPLAY=
LIBRESPOT_DISABLE_AUDIO_CACHE=
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=
LIBRESPOT_ENABLE_VOLUME_NORMALISATION=

-- Ouput of aplay -l --

**** List of PLAYBACK Hardware Devices ****
card 0: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: vc4hdmi [vc4-hdmi], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

-- Ouput of aplay -L --

null
    Discard all samples (playback) or generate zero samples (capture)
hw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct hardware device without any conversions
plughw:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Hardware device with all software conversions
default:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
sysdefault:CARD=Headphones
    bcm2835 Headphones, bcm2835 Headphones
    Default Audio Device
dmix:CARD=Headphones,DEV=0
    bcm2835 Headphones, bcm2835 Headphones
    Direct sample mixing device
hw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct hardware device without any conversions
plughw:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Hardware device with all software conversions
default:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
sysdefault:CARD=vc4hdmi
    vc4-hdmi, MAI PCM i2s-hifi-0
    Default Audio Device
hdmi:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    HDMI Audio Output
dmix:CARD=vc4hdmi,DEV=0
    vc4-hdmi, MAI PCM i2s-hifi-0
    Direct sample mixing device

-- Ouput of librespot -d ? --


	Compatible alsa device(s):

	--------------------------------------------------------------------

	Device:

		hw:CARD=Headphones,DEV=0

	Description:

		bcm2835 Headphones, bcm2835 Headphones
		Direct hardware device without any conversions

	Supported Format & Sample Rate Combinations:

		Format: S16   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz

	--------------------------------------------------------------------

	Device:

		plughw:CARD=Headphones,DEV=0

	Description:

		bcm2835 Headphones, bcm2835 Headphones
		Hardware device with all software conversions

	Supported Format & Sample Rate Combinations:

		Format: S16   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S24   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S24_3 Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S32   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: F32   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: F64   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz

	--------------------------------------------------------------------

	Device:

		default:CARD=Headphones

	Description:

		bcm2835 Headphones, bcm2835 Headphones
		Default Audio Device

	Supported Format & Sample Rate Combinations:

		Format: S16   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S24   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S24_3 Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S32   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: F32   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: F64   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz

	--------------------------------------------------------------------

	Device:

		sysdefault:CARD=Headphones

	Description:

		bcm2835 Headphones, bcm2835 Headphones
		Default Audio Device

	Supported Format & Sample Rate Combinations:

		Format: S16   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S24   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S24_3 Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: S32   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: F32   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz
		Format: F64   Sample Rate(s): 44.1kHz, 48kHz, 88.2kHz, 96kHz

	--------------------------------------------------------------------

	Device:

		dmix:CARD=Headphones,DEV=0

	Description:

		bcm2835 Headphones, bcm2835 Headphones
		Direct sample mixing device

	Supported Format & Sample Rate Combinations:

		Format: S16   Sample Rate(s): 48kHz

	--------------------------------------------------------------------
```

### LINKED ISSUE #670: The music doesn't play, it just scrolls
### Compatible Device

- [X] I'm running Raspotify on a compatible Device

### Are you sure?

- [X] I'm not trying to run Raspotify on a ARMv6 device

### Compatible OS

- [X] I'm running Raspotify on a compatible OS

### Compatible Configuration

- [X] I'm running Raspotify on a compatible Configuration

### Latest Version

- [X] I'm running the latest version of Raspotify

### Are you sure?

- [X] I'm not running Raspotify 0.31.8.1 on a Pi v1 or Pi Zero

### Due Diligence

- [X] I have done my due diligence

### What happened?

I wanted to play some music but for a few days now all I've gotten is the songs scrolling to the next one and so on and so forth. Despite reinstalling the software and the entire system on the raspberry pi 4, it didn't work.

https://github.com/user-attachments/assets/f29e2d1a-015c-4866-83fd-a703d44b6acc

Just like in the movie, it changes by itself

### Relevant log output and/or the contents of /etc/raspotify/crash_report if any ( sudo journalctl -u raspotify -b and sudo cat /etc/raspotify/crash_report )

```shell
Sep 03 19:05:33 raspberrypi systemd[1]: Started raspotify.service - Raspotify (Spotify Connect Client).
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 53036561475767057797983400620817241747, audio_>
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 126259601155372878568949598867005957397, audio>
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 54447610324500953573142913273729978295, audio_>
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 169521179732277629243290927173932916245, audio>
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 232225039897052614237254781094114445023, audio>
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 162028838171401467589615975255244950578, audio>
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:09 raspberrypi librespot[668]: [2024-09-03T17:07:09Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 140730357199516279583465159941361576804, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 208250368773906942889955416341451553453, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 5713765856195359562657769183685188797, audio_t>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 28920153809481008829636237664955493168, audio_>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 264774973186793444400250663909453871900, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 188930730237638063465794986525012297695, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 61201146394670731678103825088990558456, audio_>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 291908172769149665851632943799263535304, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 279227199881009651727523141785025869353, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 215306371885541599569871161141011996808, audio>
Sep 03 19:07:10 raspberrypi librespot[668]: [2024-09-03T17:07:10Z ERROR librespot_core::channel] channel error: 2 0
```

### PR DESCRIPTION
**Pull request by kimtore**
This patch uses upstream dev branch in favor of Jason's fork.

~The dev branch merged cleanly into that fork, and there was no diff between the two trees.~

The commit trees for the fork and upstream diverge. Many commits won't merge because of conflicts. Some code seems similar on both sides. I have no idea about the potential breakage for downstream users, but the alternative is to leave it unmaintained. Hopefully everything works fine :-)

Fixes #670
Fixes #669

### CODE REVIEW

**Comment by dtcooper** [comment]
Looks good! Go ahead an yourself to the LICENSE file, and we'll merge!

File: build.sh [hunk 1]
```diff
@@ -60,17 +57,25 @@ packages() {
...
+	# We really should use the git rev of librespot for .deb versioning.
+	# The latest tag as of writing (0.4.2) is misleading because it doesn't reflect
+	# the fact we are using the dev branch (staged for 0.5.0).
+	#
+	# Hardcoding 0.5.0-dev in combination with the git hash suffix seems to be an
+	# acceptable solution as long as the raspotify version also is bumped every
+	# time we update against librespot.
+	#
+	#LIBRESPOT_VER="$(git describe --tags "$(git rev-list --tags --max-count=1)" 2>/dev/null || echo unknown)"
+	LIBRESPOT_VER=0.5.0-dev
```
Comment (dtcooper) [inline build.sh:69]: Prefix `LIBRESPOT_VER` with a `v` to provide similarly named packages as before.

File: build.sh [hunk 2]
```diff
@@ -37,17 +37,14 @@ packages() {
...
-		git clone https://github.com/JasonLG1979/librespot
-		cd librespot
-		git checkout raspotify
+		echo "Get https://github.com/librespot-org/librespot/tree/dev..."
+		git clone --branch dev https://github.com/librespot-org/librespot
 		cd /mnt/raspotify
 	fi
 
+	# Quelch warning about dubious ownership
+	git config --global --add safe.directory /mnt/raspotify/librespot
```
Comment (dtcooper) [inline build.sh:46]: Are you using Docker in rootless mode? I designed Raspotify _before_ rootless was available, and I'm noticing "dubious" ownership as well. Perhaps below we can check if the UID is high, and only apply the "permfix" if necessary. (Lines 189-190 after your changes)

```bash
# Perm fixup. Not needed on macOS, but is on Linux
chown -R "$PERMFIX_UID:$PERMFIX_GID" /mnt/raspotify 2>/dev/null || true
```

**Review by dtcooper — APPROVED** [review]
Looks good, could you address the feedback? :)

**Comment by kimtore** [comment]
I overlooked the fact that I had a previously checked out copy of librespot 0.4.2 in raspotify's directory. Therefore leading me to believe that I compiled against 0.5.0 when in fact I was not.

Anyways, the updated PR builds against upstream `dev` branch and should address the issues you pointed out.

**Comment by dtcooper** [comment]
LGTM. Merged and cutting a release. Hopefully it works! :)

**Comment by dtcooper** [comment]
Cutting as v0.44.0.
